variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

default:
  image: node:16-slim

lint:
  stage: test
  script:
    - npm run lint
    - npm run lint:styles

deploy:
  stage: deploy
  before_script:
     # Install ssh if not already
     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
     - eval $(ssh-agent -s)
     # Make SSH key available
     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     # Add known host keys
     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
     - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh gitdeploy@dreamcast.neuf.no "$(< bin/deploy)"
  only:
    - main
